[Alembic]
script_location = migrations

file_template = %%(year)d_%%(month)02d_%%(day)02d_%%(hour)02d_%%(minute)02d_%%(second)02d_%%(slug)s

timezone = UTC

truncate_slug_length = 40

revision_environment = false

version_locations = migrations/versions

sqlalchemy.url = postgresql://chronos_user:chronos_pass@localhost:5432/chronos

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S